board_manager:
  additional_urls: []
daemon:
  port: :50051
directories:
  data: ./arduino15/data
  downloads: ../arduino15/downloads
  user: ./arduino15/local
library:
  enable_unsafe_install: true
logging:
  file: ""
  format: text
  level: info
metrics:
  addr: :9090
  enabled: true
updater:
  enable_notification: true