board_manager:
  additional_urls: []
daemon:
  port: "50051"
directories:
  data: "./data"
  downloads: "./staging"
  user: "./sketchbook"
library:
  enable_unsafe_install: true
logging:
  file: ""
  format: text
  level: info
metrics:
  addr: :9090
  enabled: true
updater:
  enable_notification: true