###################################################
#                                                 #
#             Gesture Controlled Robot            #
#                                                 #
###################################################
# author  : Cornel Cristea                        #
# date    : 22/06/2024                            #
# version : 1.0.0                                 #
###################################################

name: Build

run-name: ${{ github.event.pull_request.title }}
on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: windows-2022

    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino platform
        run : start_console a

      - name: Install project libraries
        run : start_console l

      - name: Compile
        run : start_console b

