###################################################
#                                                 #
#             Gesture Controlled Robot            #
#                                                 #
###################################################
# author  : Cornel Cristea                        #
# date    : 22/06/2024                            #
# version : 1.0.0                                 #
###################################################

name: Build

run-name: ${{ github.event.pull_request.title }}
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-2022
    env:
      BOARD_NAME: nano
      PLATFORM_NAME: avr
      PLATFORM_VERSION: 1.8.6

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies
        shell: cmd
        run: |
          set "PATH=%GITHUB_WORKSPACE%\tools\arduino-cli;%PATH%"
          arduino-cli core install arduino:%PLATFORM_NAME%@%PLATFORM_VERSION% --config-file %GITHUB_WORKSPACE%\config.yml

      - name: Install libraries
        shell: cmd
        run: |
          set "PATH=%GITHUB_WORKSPACE%\tools\arduino-cli;%PATH%"
          for %%f in ("%GITHUB_WORKSPACE%\lib\*.zip") do (
              arduino-cli lib install --config-file %GITHUB_WORKSPACE%\config.yml --zip-path %%f
          )
          
      - name: Compile
        shell: cmd
        run: |
          set "PATH=%GITHUB_WORKSPACE%\tools\arduino-cli;%PATH%"
          arduino-cli compile -v -b arduino:%PLATFORM_NAME%:%BOARD_NAME% %GITHUB_WORKSPACE%\src\robot --config-file %GITHUB_WORKSPACE%\config.yml --output-dir %GITHUB_WORKSPACE%\build
          arduino-cli compile -v -b arduino:%PLATFORM_NAME%:%BOARD_NAME% %GITHUB_WORKSPACE%\src\controller --config-file %GITHUB_WORKSPACE%\config.yml --output-dir %GITHUB_WORKSPACE%\build