###################################################
#                                                 #
#             Gesture Controlled Robot            #
#                                                 #
###################################################
# author  : Cornel Cristea                        #
# date    : 22/06/2024                            #
# version : 1.0.0                                 #
###################################################

name: Pull Request

run-name: ${{ github.event.head_commit.message || github.event.pull_request.title || 'Unknown' }}
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Pull_Request:
    name: Pull Request
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rebuild
        run: |
          cd $GITHUB_WORKSPACE
          cd 
          start_console b

      - name: Check binary files
        run: | 
          cd $GITHUB_WORKSPACE
          dir build