###################################################
#                                                 #
#             Gesture Controlled Robot            #
#                                                 #
###################################################
# author  : Cornel Cristea                        #
# date    : 22/06/2024                            #
# version : 1.0.0                                 #
###################################################

name: Pull Request

run-name: ${{ github.event.pull_request.title || github.event.head_commit.message ||  'Unknown' }}
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Pull Request
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up environment
        shell: cmd
        run: |
          set "PATH=%GITHUB_WORKSPACE%\tools\arduino-cli;%GITHUB_WORKSPACE%\tools\7-zip;%PATH%"

      - name: Build
        shell: cmd
        run: |
          cd %GITHUB_WORKSPACE%
          start_console.bat b

      - name: Check binary files
        shell: cmd
        run: | 
          cd %GITHUB_WORKSPACE%
          dir build