###################################################
#                                                 #
#             Gesture Controlled Robot            #
#                                                 #
###################################################
# author  : Cornel Cristea                        #
# date    : 22/06/2024                            #
# version : 1.0.0                                 #
###################################################

name: Release

run-name: Gesture-Controlled-Robot
on:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "Set the project version for this release (e.g. 2.0)"
        required: true

jobs:
  release:
    name: Release
    runs-on: windows-2022
    env:
      RELEASE_BRANCH: release/v${{ github.event.inputs.VERSION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        shell: cmd
        run : start_console.bat b

      - name: Create package
        shell: cmd
        run : start_console.bat r

      - name: Update repository
        shell: cmd
        run: |
          git checkout -b %RELEASE_BRANCH%
          git add binary_files.zip
          git commit -m "upload zip archive"
          git push origin %RELEASE_BRANCH%
          git merge to main
          git checkout main
          git merge %RELEASE_BRANCH%
          git push origin main

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: binary_files
          path: ./binary_files.zip