###################################################
#                                                 #
#             Gesture Controlled Robot            #
#                                                 #
###################################################
# author  : Cornel Cristea                        #
# date    : 22/06/2024                            #
# version : 1.0.0                                 #
###################################################

name: Release

run-name: Release
on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: "Set the project version for this release (e.g. 2.0)"
        required: true

jobs:
  release:
    name: Release
    runs-on: windows-2022

    env:
      RELEASE_TAG: v${{ github.event.inputs.RELEASE_VERSION }}
      RELEASE_BRANCH: release/%RELEASE_TAG%
      TARGET_BRANCH: main
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino
        shell: cmd
        run : start_console a

      - name: Install project libraries
        shell: cmd
        run : start_console l

      - name: Build
        shell: cmd
        run : start_console b

      - name: Create package
        shell: cmd
        run : start_console r

      - name: Update repository
        shell: cmd
        run: |
          git checkout -b %RELEASE_BRANCH%
          git add binary_files.zip
          git commit -m "upload zip archive"
          git push origin %RELEASE_BRANCH%
          
          git checkout %TARGET_BRANCH%
          git merge %RELEASE_BRANCH%
          
          git tag %RELEASE_TAG%
          git push origin %TARGET_BRANCH% %RELEASE_TAG%

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: binary_files
          path: ./binary_files.zip