###################################################
#                                                 #
#             Gesture Controlled Robot            #
#                                                 #
###################################################
# author  : Cornel Cristea                        #
# date    : 22/06/2024                            #
# version : 1.0.0                                 #
###################################################

name: Release

run-name: Release
on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: "Set the project version for this release (e.g. 2.0)"
        required: true

jobs:
  create-package:
    name: Release_v${{ github.event.inputs.RELEASE_VERSION }}
    runs-on: windows-2022

    defaults:
      run:
        shell: cmd

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USER: ${{ secrets.ACTIONS_USER }}
      GITHUB_EMAIL: ${{ secrets.ACTIONS_EMAIL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino platform
        run : start_console a

      - name: Install project libraries
        run : start_console l

      - name: Build
        run : start_console b

      - name: Create package
        run : start_console r

      - name: Push changes
        run: |
          set RELEASE_BRANCH=release/v${{ github.event.inputs.RELEASE_VERSION }}

          git config --global user.name "%GITHUB_USER%"
          git config --global user.email "%GITHUB_EMAIL%"

          git diff --exit-code || (
            git checkout -b %RELEASE_BRANCH%
            git add .
            git commit -m "v${{ github.event.inputs.RELEASE_VERSION }}"
            git push https://x-access-token:%GITHUB_TOKEN%@github.com/${{ github.repository }} "%RELEASE_BRANCH%"
          )
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: binary_files
          path: ./binary_files.zip