###################################################
#                                                 #
#             Gesture Controlled Robot            #
#                                                 #
###################################################
# author  : Cornel Cristea                        #
# date    : 22/06/2024                            #
# version : 1.0.0                                 #
###################################################

name: Release

run-name: Release
on:
  workflow_dispatch:
    inputs:
      RELEASE_VERSION:
        description: "Set the project version for this release (e.g. 2.0)"
        required: true

jobs:
  release:
    name: v${{ github.event.inputs.RELEASE_VERSION }}
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Arduino platform
        shell: cmd
        run : start_console a

      - name: Install project libraries
        shell: cmd
        run : start_console l

      - name: Build
        shell: cmd
        run : start_console b

      - name: Create package
        shell: cmd
        run : start_console r

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USER: GitHub Actions Bot
          GITHUB_EMAIL: actions@github.com
        shell: cmd
        run: |
          set RELEASE_BRANCH=release/v${{ github.event.inputs.RELEASE_VERSION }}

          git config --global user.name "%GITHUB_USER%"
          git config --global user.email "%GITHUB_EMAIL%"

          git checkout -b %RELEASE_BRANCH%
          git add .
          git commit -m "upload zip archive"
          git push https://x-access-token:%GITHUB_TOKEN%@github.com/${{ github.repository }} "%RELEASE_BRANCH%"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with: 
          name: binary_files.zip
          path: ./binary_files.zip